#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bash /home/zabit/.config/polybar/launch.sh --forest &

wal -R &
bash wal --theme base16-nord &

bspc monitor -d I II III IV V VI 

bspc config border_width        3
bspc config window_gap          5
bspc config focused_border_color \#4ADEDE
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

feh --bg-fill /home/zabit/suckless/wallpapers/repo/Wallhaven/Arch\ Logo\ 4.png
